### ISSUE TITLE
game window does not load

### ISSUE THREAD

**Issue by maksimka5367** [kaiserdj/Darkorbit-client#25]
After restarting the game server, it is not possible to enter the game. Loads the loading window and nothing happens. Previously there was such a problem, but it was solved somehow by itself. I am using the latest version

<img width="1280" alt="Снимок экрана 2021-05-11 в 19 31 45" src="https://user-images.githubusercontent.com/84034847/117853010-96cd3e00-b290-11eb-9ccb-b9416eef91e7.png">

**Comment by kaiserdj** [comment]
I just published an update with a new option to clear cache, I hope this will solve your problem.
https://github.com/kaiserdj/Darkorbit-client/releases/tag/v2.2.1

You can also delete the client data, deleting the darkorbit-client folder that is located in AppData / Roaming

I'm sorry I was late in updating the application, lately I am very busy

**Comment by kaiserdj** [comment]
I close the issue, if you have problems again please open it again

**Comment by Bradara** [comment]
Sorry but the problem persist!
How to clear cashe in Linux?
How to clear cashe in game window?

**Comment by kaiserdj** [comment]
![image](https://user-images.githubusercontent.com/5487950/119962652-911d6b00-bfa7-11eb-9d3d-9f33ec282410.png)
In the notification bars of the operating system, you will have an icon with the launcher. By right clicking you will have several options and one of them is to clear the cache

**Comment by Bradara** [comment]
Yes, thanks. I did it. 
After a couple of clearing, changing the language to "English" and manual logout.
